server:
  port: 8080
spring:
  application:
    name: "MsUmanoProductsManagement"
  webflux:
    base-path: "api/v1/umano"
  profiles:
    active: "${ENV:local}"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
umano:
  paths:
    list: "/products"
    list-by-id: "/product/{id}"
    create: "/product"
    update: "/product"
    delete: "/product/{id}"
    deleteAll: "/products"
aws:
  dynamodb:
    endpoint: "http://localhost:8010"
    threads: "10"
    region: "us-east-1"
    table-name: umano-table-local
